# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
#     container: circleci/mongo:latest
#     container: cimg/node:current-browsers

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       steps:
      #install chrome
#       - run: sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
#       - run: sudo echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
#       - run: sudo apt-get -y update
  
      
      - run: sudo apt-get -y install google-chrome-stable
      - run: whereis google-chrome
      - run: wget https://chromedriver.storage.googleapis.com/100.0.4896.60/chromedriver_linux64.zip
      - run: unzip chromedriver_linux64.zip
      - run: sudo mv chromedriver /usr/bin/chromedriver
      - run: sudo chown root:root /usr/bin/chromedriver
      - run: sudo chmod +x /usr/bin/chromedriver
      - run: sudo apt-get install xvfb
#       - run: chrome --version
      - uses: actions/checkout@v3
      - run: ls
      #checkout web-mpc
      - run: git submodule init 
      - run: git submodule update
      #checkout jiff
      - run: ls
      - run: cd web-mpc
      - run: ls
      - run: git submodule init 
        working-directory: web-mpc
      - run: git submodule update
        working-directory: web-mpc
      #restore deps
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-de
      
      #install deps
      - run: ls
      - run: npm ci
        working-directory: web-mpc
#       - run: cd jiff
      - run: npm ci
        working-directory: web-mpc/jiff
      - run: cd ..
      #cache deps
      #not implemented
      
      #run tests
#       - run: npm install --save selenium-webdriver chromedriver
#       - run: ls
      - run: Xvfb :1 -screen 0 1024x768x24 & export DISPLAY=:1
#       - run: node test/selenium/small_test.js
      - run: npm run test
        working-directory: web-mpc
      
      #done
      - run: echo Done
